version: '3.2'

services:
  
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  
  producer:
    build: producer
    volumes:
      - ./producer:/app
    environment:
      - PYTHONUNBUFFERED=1
  
  ride_matching_consumer:
    build: ride_matching_consumer
    volumes:
      - ./ride_matching_consumer:/app
    ports:
      - 5000:5000
  
  #database_consumer:
  #  build: database_consumer
  #  volumes:
  #    - ./database_consumer:/app
  #  ports:
  #    - 6000:6000
    
